INSERT INTO COORDINATES (COORDINATES_ID, r, x, y) VALUES (1, 1, 1, 1);
INSERT INTO COORDINATES (COORDINATES_ID, r, x, y) VALUES (2, 2, 2, 2);
INSERT INTO COORDINATES (COORDINATES_ID, r, x, y) VALUES (3, 3, 3, 3);